version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
      - image: circleci/mysql:8.0
    environment:
      - DB_CONNECTION: circle_testing
      - MYSQL_ROOT_HOST: '%'
      - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - run: composer install -n --prefer-dist --working-dir=./src
      - run:
          command: npm ci
          working_directory: src
      - run: 
          command: npm run dev
          working_directory: src
      - run:
          name: php test
          working_directory: src
          command: vendor/bin/phpunit