version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
      - image: circleci/mysql:8.0
    environment:
      - DB_CONNECTION: circle_testing
      - MYSQL_ROOT_HOST: '%'
      - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./src
      - save_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "src/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
          working_directory: src 
      - save_cache:
          key: npm-v1-{{ checksum "src/package-lock.json" }}
          paths:
            - node_modules
      - run: 
          command: npm run dev
          working_directory: src
      - run:
          name: php test
          working_directory: src
          command: vendor/bin/phpunit