version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
      - image: circleci/mysql:8.0
    environment:
      - DB_CONNECTION: test_mysql
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist --working-dir=./src
      - run:
          command: npm ci
          working_directory: src
      - run: 
          command: npm run dev
          working_directory: src

      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: src